---
GenerationParams:
  MapScale: 1.0          # how much the sectors are spread out  
  # float [0..1] solar systems are more like a cookie than a ball. the lower the value, the flatter the system
  SolarSystemSqueezeMinMax: [0.005, 0.35]
  # float [0..1] probability a warp connection will be one-way
  OneWayWarpProb: 0
  UniqueStarterPlanet: false
  
  #==== 1st Step of SolarSystem Generation: setting amount and playfield types  for System Content  ===

  PlanetCountProbs:
# ======================================================================================================================================================== Planets

# -------------------------------------------------------------------------------------------------------------------------------------------------------- Gas Giants
     - '0 : 1.0,   1 : 0.0,  2 : 0.0,  3 : 0.0,  4 : 0.0,  5 : 0.0,  6 : 0.0,  7 : 0.0,  8 : 0.0'                 # 1 - Gas Planets
     - '0 : 0.5,   1 : 0.3,  2 : 0.2,  3 : 0.0,  4 : 0.0,  5 : 0.0,  6 : 0.0,  7 : 0.0,  8 : 0.0'                 # 2 - Outer Gas Planets

# -------------------------------------------------------------------------------------------------------------------------------------------------------- Stars
     # - '0 : 0.0,   1 : 1.0,  2 : 0.0,  3 : 0.0,  4 : 0.0,  5 : 0.0,  6 : 0.0,  7 : 0.0,  8 : 0.0'                 # 1 - M type Red Dwarf

# -------------------------------------------------------------------------------------------------------------------------------------------------------- Rocky Planets
     - '0 : 0.8,   1 : 0.2,  2 : 0.0,  3 : 0.0,  4 : 0.0,  5 : 0.0,  6 : 0.0,  7 : 0.0,  8 : 0.0'                 # 1 - Hot
     - '0 : 0.7,   1 : 0.3,  2 : 0.0,  3 : 0.0,  4 : 0.0,  5 : 0.0,  6 : 0.0,  7 : 0.0,  8 : 0.0'                 # 2 - Desert
     - '0 : 0.9,   1 : 0.1,  2 : 0.2,  3 : 0.0,  4 : 0.0,  5 : 0.0,  6 : 0.0,  7 : 0.0,  8 : 0.0'                 # 3 - Dead
     - '0 : 0.7,   1 : 0.3,  2 : 0.0,  3 : 0.0,  4 : 0.0,  5 : 0.0,  6 : 0.0,  7 : 0.0,  8 : 0.0'                 # 4 - Temperate
     - '0 : 1.0,   1 : 0.0,  2 : 0.0,  3 : 0.0,  4 : 0.0,  5 : 0.0,  6 : 0.0,  7 : 0.0,  8 : 0.0'                 # 5 - Ocean
     - '0 : 0.8,   1 : 0.2,  2 : 0.0,  3 : 0.0,  4 : 0.0,  5 : 0.0,  6 : 0.0,  7 : 0.0,  8 : 0.0'                 # 6 - Alien
     - '0 : 0.3,   1 : 0.5,  2 : 0.2,  3 : 0.0,  4 : 0.0,  5 : 0.0,  6 : 0.0,  7 : 0.0,  8 : 0.0'                 # 7 - Snow
     - '0 : 0.7,   1 : 0.3,  2 : 0.0,  3 : 0.0,  4 : 0.0,  5 : 0.0,  6 : 0.0,  7 : 0.0,  8 : 0.0'                 # 8 - Barren
     - '0 : 1.0,   1 : 0.0,  2 : 0.0,  3 : 0.0,  4 : 0.0,  5 : 0.0,  6 : 0.0,  7 : 0.0,  8 : 0.0'                 # 9 - Exotic

# ======================================================================================================================================================== Sector POIs
# ------------------------------------------------------------------------------------------------- Main
     - '0 : 0.3,   1 : 0.7,  2 : 0.0,  3 : 0.0,  4 : 0.0,  5 : 0.0,  6 : 0.0,  7 : 0.0,  8 : 0.0'                              # 1 - Trading Station

# -------------------------------------------------------------------------------------------------------------------------------------------------------- UCH and Admin POIs
     - '0 : 0.95,   1 : 0.05,  2 : 0.0,  3 : 0.0,  4 : 0.0,  5 : 0.0,  6 : 0.0,  7 : 0.0,  8 : 0.0'               # 1 - UCH Research Vessel

# -------------------------------------------------------------------------------------------------------------------------------------------------------- Asteroid Fields
     - '0 : 0.0,   1 : 0.3,  2 : 0.5,  3 : 0.2,  4 : 0.0,  5 : 0.0,  6 : 0.0,  7 : 0.0,  8 : 0.0'                 # 1 - Asteroid Fields
     - '0 : 0.6,   1 : 0.2,  2 : 0.1,  3 : 0.1,  4 : 0.0,  5 : 0.0,  6 : 0.0,  7 : 0.0,  8 : 0.0'                 # 2 - Ice Fields

# -------------------------------------------------------------------------------------------------------------------------------------------------------- Stations
     - '0 : 1.0,   1 : 0.0,  2 : 0.0,  3 : 0.0,  4 : 0.0,  5 : 0.0,  6 : 0.0,  7 : 0.0,  8 : 0.0'                 # 1 - Polaris Trade Station

# -------------------------------------------------------------------------------------------------------------------------------------------------------- Anomalies

# -------------------------------------------------------------------------------------------------------------------------------------------------------- Events
     - '0 : 0.9,   1 : 0.1,  2 : 0.0,  3 : 0.0,  4 : 0.0,  5 : 0.0,  6 : 0.0,  7 : 0.0,  8 : 0.0'                 # 1 - Random Events



  PlanetLists:           # Lable name depicts, in a descriptive way, the class or global or visual approach of the playfields summarized under this lable; playfields are added in the *Types sections
# ======================================================================================================================================================== Planets

# -------------------------------------------------------------------------------------------------------------- Gas Giants
    - 'JupiterDrone:0.6, SaturnDrone: 0.4'                                                                                  # 1 Gas
    - 'JupiterOuterDrone:0.45, SaturnOuterDrone:0.35, NeptuneOuterDrone:0.2'                                                     # 2 Gas Outer
# -------------------------------------------------------------------------------------------------------------- Stars
    # - 'StarM:1'                                                                                                   # 1 M type Red Dwarf
# -------------------------------------------------------------------------------------------------------------- Rocky Planets
    - 'Lava:0.6, Lava2:0.35, Midnight:0.05'                                                                       # 1 Hot
    - 'Desert:0.6, Arid:0.4, DesertOasis:0.0, DesertBlack:0.0'                                                    # 2 Desert
    - 'Dead:1'                                                                                                    # 3 Dead
    - 'Temperate:0.8, Tropical:0.0, Swamp:0.2, Irradiated:0.0, Jungle:0.0'                                        # 4 Temperate
    - 'Ocean:1'                                                                                                   # 5 Ocean
    - 'Alien:1'                                                                                                   # 6 Alien
    - 'Snow:0.2, Ice:0.8'                                                                                         # 7 Snow
    - 'Barren:1.0, BarrenHot:0.0'                                                                                 # 8 Barren
    - 'Plasma:1, AlienLegacy:0.0, ProgenitorCore:0.0, IceGiant: 0.0'                                              # 9 Exotic
# ======================================================================================================================================================== Sector POIs
# ------------------------------------------------------------------------------------------------- Main
    - 'TradingStationMain:1'              # 1 Trading Station
# -------------------------------------------------------------------------------------------------------------- UCH and Admin
    - 'UCHResearchShip:1.0'                                                                                       # 1 UCH Research Vessel
# -------------------------------------------------------------------------------------------------------------- Asteroid Fields
    - 'AsteroidFieldDrone:1.0, AsteroidFieldPirate:0.0, AsteroidFieldPolaris:0.0, AsteroidFieldZirax:0.0'              # 1 Asteroid Fields
    - 'AsteroidFieldIce:1.00, AsteroidFieldIceRich:0.00'                                                          # 2 Ice Fields

# -------------------------------------------------------------------------------------------------------------- Stations
    - 'TradeStationPolaris:1.0'                                                                                   # 1 Polaris Trade Station

# -------------------------------------------------------------------------------------------------------------- Anomalies
# -------------------------------------------------------------------------------------------------------------- Events
    - 'PentaxidMining:0.0, SyndicateCasino:0.0, XenuanCarrier:1.0'                                                # 1 Random Events



# ======================================================================================================================================================== POIs
  POICountProbs: '0 : 0.20,  1 : 0.40,  2 : 0.20,  3 : 0.00,  4 : 0.00,  5 : 0.00,  6 : 0.00,  7 : 0.10,  8: 0.10'
# -------------------------------------------------------------------------------------------------------------------------------------------------------- POI counts
  POIs: 'SpaceEmpty: 0.00, POICombatT2: 0.30, POIExploreT1: 0.40, POIMiningT4Drone: 0.30'
# --------------------------------------------------------------------------------------------------------------------------------------------------------

# =================================================================================================================================================================================
#                                                                                                                POIs
# =================================================================================================================================================================================
  POITypes:

# ======================================================================================================================================================================================================
# ================================================================================================================================================================================= Random Sector POIs
# ======================================================================================================================================================================================================

# -------------------------------------------------------------------------- SpaceEmpty
      - Name: SpaceEmpty
        Color: [0.3, 0.3, 0.3]
        Icon: Triangle
        Placement:
            - InnerSystem
            - HabitableHot
            - HabitableTemperate
            - HabitableCold
            - OuterSystem
        HasOrbit: false
        HasTerrain: false
        PlayfieldLevel: [2,6]
        Playfields:
            - SpaceEmpty

# -------------------------------------------------------------------------- POI_Combat
      - Name: POI_Combat
        Icon: Triangle
        Color: [1, 0, 0]
        Placement:
            - InnerSystem
            - HabitableHot
            - HabitableTemperate
            - HabitableCold
            - OuterSystem
        HasOrbit: false
        HasTerrain: false
        PlayfieldLevel: [2,6]
        Playfields:
            - SpaceEmpty

# -------------------------------------------------------------------------- POI_Exploration
      - Name: POI_Exploration
        Icon: Triangle
        Color: [0, 1, 0.7]
        Placement:
            - InnerSystem
            - HabitableHot
            - HabitableTemperate
            - HabitableCold
            - OuterSystem
        HasOrbit: false
        HasTerrain: false
        PlayfieldLevel: [2,6]
        Playfields:
            - SpaceEmpty

# -------------------------------------------------------------------------- POI_Mining
      - Name: POI_Mining
        Icon: Triangle
        Color: [0.62, 0.32, 0.17]
        Placement:
            - InnerSystem
            - HabitableHot
            - HabitableTemperate
            - HabitableCold
            - OuterSystem
        HasOrbit: false
        HasTerrain: false
        PlayfieldLevel: [2,6]
        Playfields:
            - SpaceEmpty

# =================================================================================================================================================================================
#                                                                                                                Orbits
# =================================================================================================================================================================================
  OrbitTypes:
# -------------------------------------------------------------------------- DefaultOrbit
      - Name: DefaultOrbit     # definition of default name 'DefaultOrbit' is mandatory
        Color: [0.3, 0.3, 0.3]
        Distance: [270, 870]
        HasOrbit: false
        HasTerrain: false
        PlayfieldLevel: [15,20]
        Playfields:
            - EdenSpaceDrone_Orbit
            # - EdenSpaceM2_Orbit2, 0.3

  WarpTargetOrbitTypes:
# -------------------------------------------------------------------------- Sun Playfield
      - Name: WarpTarget
        Color: [0.3, 0.3, 0.3]
        Distance: [270, 870]
        HasOrbit: false
        HasTerrain: false
        PlayfieldLevel: [1,4]
        Playfields:
            - EdenSpaceWarpTargetM
