---
GenerationParams:
  MapScale: 1.0          # how much the sectors are spread out  
  # float [0..1] solar systems are more like a cookie than a ball. the lower the value, the flatter the system
  SolarSystemSqueezeMinMax: [0.005, 0.1]
  # float [0..1] probability a warp connection will be one-way
  OneWayWarpProb: 0
  UniqueStarterPlanet: false
  
  #==== 1st Step of SolarSystem Generation: setting amount and playfield types  for System Content  ===

  PlanetCountProbs:
# ======================================================================================================================================================== Planets

# -------------------------------------------------------------------------------------------------------------------------------------------------------- Gas Giants
     - '0 : 0.7,   1 : 0.3,  2 : 0.0,  3 : 0.0,  4 : 0.0,  5 : 0.0,  6 : 0.0,  7 : 0.0,  8 : 0.0'                 # 1 - Gas Planets
     - '0 : 0.8,   1 : 0.2,  2 : 0.0,  3 : 0.0,  4 : 0.0,  5 : 0.0,  6 : 0.0,  7 : 0.0,  8 : 0.0'                 # 2 - Outer Gas Planets

# -------------------------------------------------------------------------------------------------------------------------------------------------------- Stars
     - '0 : 0.85,   1 : 0.10,  2 : 0.05,  3 : 0.0,  4 : 0.0,  5 : 0.0,  6 : 0.0,  7 : 0.0,  8 : 0.0'               # 1 - Companion Stars

# -------------------------------------------------------------------------------------------------------------------------------------------------------- Rocky Planets
     - '0 : 0.9,   1 : 0.1,  2 : 0.0,  3 : 0.0,  4 : 0.0,  5 : 0.0,  6 : 0.0,  7 : 0.0,  8 : 0.0'                 # 1 - Hot
     - '0 : 0.3,   1 : 0.5,  2 : 0.1,  3 : 0.1,  4 : 0.0,  5 : 0.0,  6 : 0.0,  7 : 0.0,  8 : 0.0'                 # 2 - Desert
     - '0 : 0.8,   1 : 0.2,  2 : 0.0,  3 : 0.0,  4 : 0.0,  5 : 0.0,  6 : 0.0,  7 : 0.0,  8 : 0.0'                 # 3 - Dead
     - '0 : 0.3,   1 : 0.3,  2 : 0.2,  3 : 0.2,  4 : 0.0,  5 : 0.0,  6 : 0.0,  7 : 0.0,  8 : 0.0'                 # 4 - Temperate
     - '0 : 1.0,   1 : 0.0,  2 : 0.0,  3 : 0.0,  4 : 0.0,  5 : 0.0,  6 : 0.0,  7 : 0.0,  8 : 0.0'                 # 5 - Ocean - Added to Temperate
     - '0 : 0.9,   1 : 0.1,  2 : 0.0,  3 : 0.0,  4 : 0.0,  5 : 0.0,  6 : 0.0,  7 : 0.0,  8 : 0.0'                 # 6 - Alien
     - '0 : 0.6,   1 : 0.3,  2 : 0.1,  3 : 0.0,  4 : 0.0,  5 : 0.0,  6 : 0.0,  7 : 0.0,  8 : 0.0'                 # 7 - Snow
     - '0 : 0.3,   1 : 0.5,  2 : 0.2,  3 : 0.0,  4 : 0.0,  5 : 0.0,  6 : 0.0,  7 : 0.0,  8 : 0.0'                 # 8 - Barren
     - '0 : 1.0,   1 : 0.0,  2 : 0.0,  3 : 0.0,  4 : 0.0,  5 : 0.0,  6 : 0.0,  7 : 0.0,  8 : 0.0'                 # 9 - Exotic

# ======================================================================================================================================================== Sector POIs
# ------------------------------------------------------------------------------------------------- Main
     - '0 : 0.3,   1 : 0.7,  2 : 0.0,  3 : 0.0,  4 : 0.0,  5 : 0.0,  6 : 0.0,  7 : 0.0,  8 : 0.0'                              # 1 - Trading Station
# ------------------------------------------------------------------------------------------------- Zirax
     - '0 : 1.0,   1 : 0.0,  2 : 0.0,  3 : 0.0,  4 : 0.0,  5 : 0.0,  6 : 0.0,  7 : 0.0,  8 : 0.0'                              # 1 - Asteroid Fields
# ------------------------------------------------------------------------------------------------- Polaris
     - '0 : 0.6,   1 : 0.3,  2 : 0.1,  3 : 0.0,  4 : 0.0,  5 : 0.0,  6 : 0.0,  7 : 0.0,  8 : 0.0'                              # 1 - Asteroid Fields
# ------------------------------------------------------------------------------------------------- Trader

# ------------------------------------------------------------------------------------------------- Colonists

# ------------------------------------------------------------------------------------------------- Pirates
     - '0 : 0.4,   1 : 0.4,  2 : 0.2,  3 : 0.0,  4 : 0.0,  5 : 0.0,  6 : 0.0,  7 : 0.0,  8 : 0.0'                              # 1 - Asteroid Fields
# ------------------------------------------------------------------------------------------------- Warlord

# ------------------------------------------------------------------------------------------------- Alien

# -------------------------------------------------------------------------------------------------------------------------------------------------------- UCH and Admin POIs
     - '0 : 0.7,   1 : 0.3,  2 : 0.0,  3 : 0.0,  4 : 0.0,  5 : 0.0,  6 : 0.0,  7 : 0.0,  8 : 0.0'                 # 1 - UCH Research Vessel

# -------------------------------------------------------------------------------------------------------------------------------------------------------- Asteroid Fields
     - '0 : 0.3,   1 : 0.1,  2 : 0.3,  3 : 0.3,  4 : 0.0,  5 : 0.0,  6 : 0.0,  7 : 0.0,  8 : 0.0'                 # 1 - Asteroid Fields

# -------------------------------------------------------------------------------------------------------------------------------------------------------- Stations
     - '0 : 0.7,   1 : 0.3,  2 : 0.0,  3 : 0.0,  4 : 0.0,  5 : 0.0,  6 : 0.0,  7 : 0.0,  8 : 0.0'                 # 1 - Polaris Trade Station

# -------------------------------------------------------------------------------------------------------------------------------------------------------- Anomalies

# -------------------------------------------------------------------------------------------------------------------------------------------------------- Events
     - '0 : 0.8,   1 : 0.2,  2 : 0.0,  3 : 0.0,  4 : 0.0,  5 : 0.0,  6 : 0.0,  7 : 0.0,  8 : 0.0'                 # 1 - Random Events



  PlanetLists:           # Lable name depicts, in a descriptive way, the class or global or visual approach of the playfields summarized under this lable; playfields are added in the *Types sections
# ======================================================================================================================================================== Planets

# -------------------------------------------------------------------------------------------------------------- Gas Giants
    - 'Jupiter:0.45, Saturn: 0.35, Neptune:0.2'                                                                   # 1 Gas
    - 'JupiterOuter:0.45, SaturnOuter:0.35, NeptuneOuter:0.2'                                                     # 2 Gas Outer
# -------------------------------------------------------------------------------------------------------------- Stars
    - 'SunB:0.00, SunA:0.10, SunG:0.20, SunF:0.20, SunM:0.30, SunD:0.20, SunN2:0.00, SunA4V:0.00'                 # 1 Companion Stars
# -------------------------------------------------------------------------------------------------------------- Rocky Planets
    - 'Lava:1.0, Lava2:0.0, Midnight:0.0'                                                                         # 1 Hot
    - 'Desert:0.5, Arid:0.3, DesertOasis:0.2, DesertBlack:0.0'                                                    # 2 Desert
    - 'Dead:1'                                                                                                    # 3 Dead
    - 'Temperate:0.2, Tropical:0.2, Swamp:0.1, Irradiated:0.0, Jungle:0.3, Ocean:0.2'                             # 4 Temperate
    - 'Ocean:1'                                                                                                   # 5 Ocean - Added to Temperate
    - 'Alien:1'                                                                                                   # 6 Alien
    - 'Snow:1.0, Ice:0.0'                                                                                         # 7 Snow
    - 'Barren:0.3, BarrenHot:0.7'                                                                                 # 8 Barren
    - 'Plasma:1, AlienLegacy:0.0, ProgenitorCore:0.0, IceGiant: 0.0'                                              # 9 Exotic
# ======================================================================================================================================================== Sector POIs
# ------------------------------------------------------------------------------------------------- Main
    - 'TradingStationMain:1'              # 1 Trading Station
# ------------------------------------------------------------------------------------------------- Zirax
    - 'AsteroidFieldZirax:1'              # 1 Asteroid Fields
# ------------------------------------------------------------------------------------------------- Polaris
    - 'AsteroidFieldPolaris:1'              # 1 Asteroid Fields
# ------------------------------------------------------------------------------------------------- Trader

# ------------------------------------------------------------------------------------------------- Colonists

# ------------------------------------------------------------------------------------------------- Pirates
    - 'AsteroidFieldPirate:1'              # 1 Asteroid Fields
# ------------------------------------------------------------------------------------------------- Warlord

# ------------------------------------------------------------------------------------------------- Alien

# -------------------------------------------------------------------------------------------------------------- UCH and Admin
    - 'UCHResearchShip:1.0'                                                                                         # 1 UCH Research Vessel
# -------------------------------------------------------------------------------------------------------------- Asteroid Fields
    - 'AsteroidFieldG:0.7, AsteroidFieldGPoor:0.3'              # 1 Asteroid Fields
# -------------------------------------------------------------------------------------------------------------- Stations
    - 'TradeStationPolaris:1.0'                                                                                  # 1 Polaris Trade Station

# -------------------------------------------------------------------------------------------------------------- Anomalies
# -------------------------------------------------------------------------------------------------------------- Events
    - 'PentaxidMining:0.5, SyndicateCasino:0.5, XenuanCarrier:0.0'                                               # 1 Random Events



# ======================================================================================================================================================== POIs
  POICountProbs: '0 : 0.40,  1 : 0.20,  2 : 0.20,  3 : 0.10,  4 : 0.10,  5 : 0.00,  6 : 0.00,  7 : 0.00,  8: 0.00'
# -------------------------------------------------------------------------------------------------------------------------------------------------------- POI counts
  POIs: 'SpaceEmpty: 0.00, POICombatT1: 0.30, POIExploreT1: 0.30, POIMiningT1: 0.40'
# --------------------------------------------------------------------------------------------------------------------------------------------------------



# for 3D map purposes, limit climate (optional for non-terrain types) to one of Lava, Temperate, Snow, Desert, Alien, or Barren
# =================================================================================================================================================================================
#                                                                                                                Definitions for Planets
# =================================================================================================================================================================================
  PlanetTypes:      # come up with general categories of planet (playfield) types for distance purposes

# ======================================================================================================================================================================================================
# ================================================================================================================================================================================= Ocean Planets
# ======================================================================================================================================================================================================

# -------------------------------------------------------------------------- Ocean
      - Name: Ocean
        Color: [0, 0.2, 0.8]
        Placement:
            - HabitableHot
            - HabitableTemperate
            - HabitableCold
        MoonProb: '0:0.5, 1:0.2, 2:0.2, 3:0.1'
        MoonType: [EdenMoonBarren, EdenMoonCrystal, MoonTemperate, MoonTemperate]
        OrbitType: [DefaultOrbit, OrbitTradeCivilian]
        Climate: Temperate
        PlayfieldLevel: [4,7]
        Playfields:
            - Ocean, 0.3
            - EdenOcean2, 0.3
            - EdenWater, 0.4

# =================================================================================================================================================================================
#                                                                                                                POIs
# =================================================================================================================================================================================
  POITypes:

# ======================================================================================================================================================================================================
# ================================================================================================================================================================================= Random Sector POIs
# ======================================================================================================================================================================================================

# -------------------------------------------------------------------------- SpaceEmpty
      - Name: SpaceEmpty
        Color: [0.3, 0.3, 0.3]
        Icon: Triangle
        Placement:
            - InnerSystem
            - HabitableHot
            - HabitableTemperate
            - HabitableCold
            - OuterSystem
        HasOrbit: false
        HasTerrain: false
        PlayfieldLevel: [2,6]
        Playfields:
            - SpaceEmpty

# -------------------------------------------------------------------------- POI_Combat
      - Name: POI_Combat
        Icon: Triangle
        Color: [1, 0, 0]
        Placement:
            - InnerSystem
            - HabitableHot
            - HabitableTemperate
            - HabitableCold
            - OuterSystem
        HasOrbit: false
        HasTerrain: false
        PlayfieldLevel: [2,6]
        Playfields:
            - SpaceEmpty

# -------------------------------------------------------------------------- POI_Exploration
      - Name: POI_Exploration
        Icon: Triangle
        Color: [0, 1, 0.7]
        Placement:
            - InnerSystem
            - HabitableHot
            - HabitableTemperate
            - HabitableCold
            - OuterSystem
        HasOrbit: false
        HasTerrain: false
        PlayfieldLevel: [2,6]
        Playfields:
            - EdenSpaceG_POI_ExploreEpsilon

# -------------------------------------------------------------------------- POI_Mining
      - Name: POI_Mining
        Icon: Triangle
        Color: [0.62, 0.32, 0.17]
        Placement:
            - InnerSystem
            - HabitableHot
            - HabitableTemperate
            - HabitableCold
            - OuterSystem
        HasOrbit: false
        HasTerrain: false
        PlayfieldLevel: [4,6]
        Playfields:
            - EdenSpace_POI_MiningUncommon1, 0.50
            - EdenSpace_POI_MiningUncommon2, 0.50


# =================================================================================================================================================================================
#                                                                                                                Stations
# =================================================================================================================================================================================
  # StationTypes:
      # - Name: SpaceTradingStation
        # Color: [0.7, 0.5, 0.0]
        # Icon: Station
        # Distance: [200, 300]
        # Placement: 
          # - InnerSystem
        # HasOrbit: false
        # HasTerrain: false
        # PlayfieldLevel: [2,10]
        # Playfields:
            # - SpaceTradingStation
            

# =================================================================================================================================================================================
#                                                                                                                Orbits
# =================================================================================================================================================================================
  OrbitTypes:
# -------------------------------------------------------------------------- DefaultOrbit
      - Name: DefaultOrbit     # definition of default name 'DefaultOrbit' is mandatory
        Color: [0.3, 0.3, 0.3]
        Distance: [270, 870]
        HasOrbit: false
        HasTerrain: false
        PlayfieldLevel: [2,6]
        Playfields:
            - EdenSpaceG_Orbit

# =================================================================================================================================================================================
#                                                                                                                Stations
# =================================================================================================================================================================================
  StationTypes:
      # - Name: SpaceTradingStation
        # Color: [1, 1, 1]
        # Icon: Station
        # Distance: [200, 300]
        # Placement:
            # - InnerSystem
            # - HabitableHot
            # - HabitableTemperate
            # - HabitableCold
        # HasOrbit: false
        # HasTerrain: false
        # PlayfieldLevel: [2,10]
        # Playfields:
            # # - SpaceTradingStation
            # - EdenSpace_TradingStation

  WarpTargetOrbitTypes:
# -------------------------------------------------------------------------- Sun Playfield
      - Name: WarpTarget
        Color: [0.3, 0.3, 0.3]
        Distance: [270, 870]
        HasOrbit: false
        HasTerrain: false
        PlayfieldLevel: [1,4]
        Playfields:
            - EdenSpaceWarpTargetF
