---
GenerationParams:
  MapScale: 1.0          # how much the sectors are spread out  
  # float [0..1] solar systems are more like a cookie than a ball. the lower the value, the flatter the system
  SolarSystemSqueezeMinMax: [0.15, 0.45]
  # float [0..1] probability a warp connection will be one-way
  OneWayWarpProb: 0
  UniqueStarterPlanet: false
  
  #==== 1st Step of SolarSystem Generation: setting amount and playfield types  for System Content  ===

  PlanetCountProbs:
# ======================================================================================================================================================== Planets

# -------------------------------------------------------------------------------------------------------------------------------------------------------- Gas Giants
     - '0 : 1.0,   1 : 0.0,  2 : 0.0,  3 : 0.0,  4 : 0.0,  5 : 0.0,  6 : 0.0,  7 : 0.0,  8 : 0.0'                 # 1 - Gas Planets
     - '0 : 0.8,   1 : 0.1,  2 : 0.1,  3 : 0.0,  4 : 0.0,  5 : 0.0,  6 : 0.0,  7 : 0.0,  8 : 0.0'                 # 2 - Outer Gas Planets

# -------------------------------------------------------------------------------------------------------------------------------------------------------- Stars
     # - '0 : 0.0,   1 : 1.0,  2 : 0.0,  3 : 0.0,  4 : 0.0,  5 : 0.0,  6 : 0.0,  7 : 0.0,  8 : 0.0'                 # 1 - M type Red Dwarf

# -------------------------------------------------------------------------------------------------------------------------------------------------------- Rocky Planets
     - '0 : 0.8,   1 : 0.1,  2 : 0.05,  3 : 0.05,  4 : 0.0,  5 : 0.0,  6 : 0.0,  7 : 0.0,  8 : 0.0'               # 1 - Hot
     - '0 : 1.0,   1 : 0.0,  2 : 0.0,  3 : 0.0,  4 : 0.0,  5 : 0.0,  6 : 0.0,  7 : 0.0,  8 : 0.0'                 # 2 - Desert
     - '0 : 0.8,   1 : 0.2,  2 : 0.0,  3 : 0.0,  4 : 0.0,  5 : 0.0,  6 : 0.0,  7 : 0.0,  8 : 0.0'                 # 3 - Dead
     - '0 : 1.0,   1 : 0.0,  2 : 0.0,  3 : 0.0,  4 : 0.0,  5 : 0.0,  6 : 0.0,  7 : 0.0,  8 : 0.0'                 # 4 - Temperate
     - '0 : 1.0,   1 : 0.0,  2 : 0.0,  3 : 0.0,  4 : 0.0,  5 : 0.0,  6 : 0.0,  7 : 0.0,  8 : 0.0'                 # 5 - Ocean
     - '0 : 1.0,   1 : 0.0,  2 : 0.0,  3 : 0.0,  4 : 0.0,  5 : 0.0,  6 : 0.0,  7 : 0.0,  8 : 0.0'                 # 6 - Alien
     - '0 : 0.7,   1 : 0.3,  2 : 0.0,  3 : 0.0,  4 : 0.0,  5 : 0.0,  6 : 0.0,  7 : 0.0,  8 : 0.0'                 # 7 - Snow
     - '0 : 0.7,   1 : 0.3,  2 : 0.0,  3 : 0.0,  4 : 0.0,  5 : 0.0,  6 : 0.0,  7 : 0.0,  8 : 0.0'                 # 8 - Barren
     - '0 : 0.8,   1 : 0.2,  2 : 0.0,  3 : 0.0,  4 : 0.0,  5 : 0.0,  6 : 0.0,  7 : 0.0,  8 : 0.0'                 # 9 - Exotic

# ======================================================================================================================================================== Sector POIs

# -------------------------------------------------------------------------------------------------------------------------------------------------------- UCH and Admin POIs
     - '0 : 0.9,   1 : 0.1,  2 : 0.0,  3 : 0.0,  4 : 0.0,  5 : 0.0,  6 : 0.0,  7 : 0.0,  8 : 0.0'                 # 1 - UCH Research Vessel

# -------------------------------------------------------------------------------------------------------------------------------------------------------- Asteroid Fields
     - '0 : 0.0,   1 : 0.2,  2 : 0.2,  3 : 0.2,  4 : 0.1,  5 : 0.1,  6 : 0.1,  7 : 0.1,  8 : 0.0'                 # 1 - Asteroid Fields
     - '0 : 0.6,   1 : 0.2,  2 : 0.1,  3 : 0.1,  4 : 0.0,  5 : 0.0,  6 : 0.0,  7 : 0.0,  8 : 0.0'                 # 2 - Ice Fields

# -------------------------------------------------------------------------------------------------------------------------------------------------------- Stations
     - '0 : 1.0,   1 : 0.0,  2 : 0.0,  3 : 0.0,  4 : 0.0,  5 : 0.0,  6 : 0.0,  7 : 0.0,  8 : 0.0'                 # 1 - Polaris Trade Station

# -------------------------------------------------------------------------------------------------------------------------------------------------------- Anomalies

# -------------------------------------------------------------------------------------------------------------------------------------------------------- Events
     - '0 : 0.5,   1 : 0.5,  2 : 0.0,  3 : 0.0,  4 : 0.0,  5 : 0.0,  6 : 0.0,  7 : 0.0,  8 : 0.0'                 # 1 - Random Events



  PlanetLists:           # Lable name depicts, in a descriptive way, the class or global or visual approach of the playfields summarized under this lable; playfields are added in the *Types sections
# ======================================================================================================================================================== Planets
# -------------------------------------------------------------------------------------------------------------- Gas Giants
    - 'Jupiter:0.6, Saturn: 0.4'                                                                                  # 1 Gas
    - 'JupiterOuter:0.45, SaturnOuter:0.35, NeptuneOuter:0.2'                                                     # 2 Gas Outer
# -------------------------------------------------------------------------------------------------------------- Stars
    # - 'StarM:1'                                                                                                   # 1 M type Red Dwarf
# -------------------------------------------------------------------------------------------------------------- Rocky Planets
    - 'Lava:0.4, Lava2:0.5, Midnight:0.1'                                                                         # 1 Hot
    - 'Desert:0.6, Arid:0.4, DesertOasis:0.0, DesertBlack:0.0'                                                    # 2 Desert
    - 'Dead:1'                                                                                                    # 3 Dead
    - 'Temperate:0.8, Tropical:0.0, Swamp:0.2, Irradiated:0.0, Jungle:0.0'                                        # 4 Temperate
    - 'Ocean:1'                                                                                                   # 5 Ocean
    - 'Alien:1'                                                                                                   # 6 Alien
    - 'Snow:0.0, Ice:1.0'                                                                                         # 7 Snow
    - 'Barren:1.0, BarrenHot:0.0'                                                                                 # 8 Barren
    - 'Plasma:1.0, AlienLegacy:0.0, ProgenitorCore:0.0, IceGiant: 0.0'                                            # 9 Exotic
# ======================================================================================================================================================== Sector POIs
# -------------------------------------------------------------------------------------------------------------- UCH and Admin
    - 'UCHResearchShip:1.0'                                                                                       # 1 UCH Research Vessel
# -------------------------------------------------------------------------------------------------------------- Asteroid Fields
    - 'AsteroidField:0.7, AsteroidFieldPirate:0.0, AsteroidFieldPolaris:0.0, AsteroidFieldZirax:0.0, AsteroidFieldLegacy:0.3'              # 1 Asteroid Fields
    - 'AsteroidFieldIce:0.80, AsteroidFieldIceRich:0.20'                                                          # 2 Ice Fields

# -------------------------------------------------------------------------------------------------------------- Stations
    - 'TradeStationPolaris:1.0'                                                                                   # 1 Polaris Trade Station

# -------------------------------------------------------------------------------------------------------------- Anomalies
# -------------------------------------------------------------------------------------------------------------- Events
    - 'PentaxidMining:0.0, SyndicateCasino:0.0, XenuanCarrier:0.7, CorruptedEncounter:0.3'                                                # 1 Random Events



# ======================================================================================================================================================== POIs
  POICountProbs: '0 : 0.20,  1 : 0.20,  2 : 0.20,  3 : 0.10,  4 : 0.10,  5 : 0.05,  6 : 0.05,  7 : 0.05,  8: 0.05'
# -------------------------------------------------------------------------------------------------------------------------------------------------------- POI counts
  POIs: 'SpaceEmpty: 0.00, POICombatT3: 0.30, POIExploreT3: 0.40, POIMiningT3: 0.30'
# --------------------------------------------------------------------------------------------------------------------------------------------------------


# =================================================================================================================================================================================
#                                                                                                                POIs
# =================================================================================================================================================================================
  POITypes:


# =================================================================================================================================================================================
#                                                                                                                Stations
# =================================================================================================================================================================================
  StationTypes:
      # - Name: SpaceTradingStation
        # Color: [0.7, 0.5, 0.0]
        # Icon: Station
        # Distance: [200, 300]
        # Placement: 
          # - InnerSystem
        # HasOrbit: false
        # HasTerrain: false
        # PlayfieldLevel: [2,10]
        # Playfields:
            # - SpaceTradingStation
            

# =================================================================================================================================================================================
#                                                                                                                Orbits
# =================================================================================================================================================================================
  OrbitTypes:
# -------------------------------------------------------------------------- DefaultOrbit
      - Name: DefaultOrbit     # definition of default name 'DefaultOrbit' is mandatory
        Color: [0.3, 0.3, 0.3]
        Distance: [270, 870]
        HasOrbit: false
        HasTerrain: false
        PlayfieldLevel: [6,10]
        Playfields:
            - EdenSpaceD_Orbit

  WarpTargetOrbitTypes:
# -------------------------------------------------------------------------- Sun Playfield
      - Name: WarpTarget
        Color: [0.3, 0.3, 0.3]
        Distance: [270, 870]
        HasOrbit: false
        HasTerrain: false
        PlayfieldLevel: [1,4]
        Playfields:
            - EdenSpaceWarpTargetBH
