---
GenerationParams:
  MapScale: 1.0
  SolarSystemSqueezeMinMax: [0.1, 0.5]
  OneWayWarpProb: 0
  UniqueStarterPlanet: false

  PlanetCountProbs:
# ======================================================================================================================================================== Planets

# -------------------------------------------------------------------------------------------------------------------------------------------------------- Gas Giants
     - '0 : 1.0,   1 : 0.0,  2 : 0.0,  3 : 0.0,  4 : 0.0,  5 : 0.0,  6 : 0.0,  7 : 0.0,  8 : 0.0'                 # 1 - Gas Planets
     - '0 : 0.6,   1 : 0.2,  2 : 0.01,  3 : 0.05,  4 : 0.05,  5 : 0.0,  6 : 0.0,  7 : 0.0,  8 : 0.0'              # 2 - Outer Gas Planets

# -------------------------------------------------------------------------------------------------------------------------------------------------------- Stars
     - '0 : 0.80,   1 : 0.10,  2 : 0.05,  3 : 0.05,  4 : 0.0,  5 : 0.0,  6 : 0.0,  7 : 0.0,  8 : 0.0'               # 1 - Companion Stars

# -------------------------------------------------------------------------------------------------------------------------------------------------------- Rocky Planets
     - '0 : 0.3,   1 : 0.5,  2 : 0.2,  3 : 0.0,  4 : 0.0,  5 : 0.0,  6 : 0.0,  7 : 0.0,  8 : 0.0'                 # 1 - Hot
     - '0 : 1.0,   1 : 0.0,  2 : 0.0,  3 : 0.0,  4 : 0.0,  5 : 0.0,  6 : 0.0,  7 : 0.0,  8 : 0.0'                 # 2 - Desert
     - '0 : 0.8,   1 : 0.2,  2 : 0.0,  3 : 0.0,  4 : 0.0,  5 : 0.0,  6 : 0.0,  7 : 0.0,  8 : 0.0'                 # 3 - Dead
     - '0 : 1.0,   1 : 0.0,  2 : 0.0,  3 : 0.0,  4 : 0.0,  5 : 0.0,  6 : 0.0,  7 : 0.0,  8 : 0.0'                 # 4 - Temperate
     - '0 : 1.0,   1 : 0.0,  2 : 0.0,  3 : 0.0,  4 : 0.0,  5 : 0.0,  6 : 0.0,  7 : 0.0,  8 : 0.0'                 # 5 - Ocean
     - '0 : 1.0,   1 : 0.0,  2 : 0.0,  3 : 0.0,  4 : 0.0,  5 : 0.0,  6 : 0.0,  7 : 0.0,  8 : 0.0'                 # 6 - Alien
     - '0 : 1.0,   1 : 0.0,  2 : 0.0,  3 : 0.0,  4 : 0.0,  5 : 0.0,  6 : 0.0,  7 : 0.0,  8 : 0.0'                 # 7 - Snow
     - '0 : 0.5,   1 : 0.4,  2 : 0.1,  3 : 0.0,  4 : 0.0,  5 : 0.0,  6 : 0.0,  7 : 0.0,  8 : 0.0'                 # 8 - Barren
     - '0 : 0.9,   1 : 0.1,  2 : 0.0,  3 : 0.0,  4 : 0.0,  5 : 0.0,  6 : 0.0,  7 : 0.0,  8 : 0.0'                 # 9 - Exotic
# -------------------------------------------------------------------------------------------------------------------------------------------------------- Faction Planets
     - '0 : 0.8,   1 : 0.2,  2 : 0.0,  3 : 0.0,  4 : 0.0,  5 : 0.0,  6 : 0.0,  7 : 0.0,  8 : 0.0'                 # 1 - DeadWastelanders
# ======================================================================================================================================================== Sector POIs
# ------------------------------------------------------------------------------------------------- Main
     - '0 : 1.0,   1 : 0.0,  2 : 0.0,  3 : 0.0,  4 : 0.0,  5 : 0.0,  6 : 0.0,  7 : 0.0,  8 : 0.0'                              # 1 - Trading Station
# ------------------------------------------------------------------------------------------------- Zirax

# ------------------------------------------------------------------------------------------------- Polaris

# ------------------------------------------------------------------------------------------------- Trader

# ------------------------------------------------------------------------------------------------- Colonists
     - '0 : 0.8,   1 : 0.2,  2 : 0.0,  3 : 0.0,  4 : 0.0,  5 : 0.0,  6 : 0.0,  7 : 0.0,  8 : 0.0'
# ------------------------------------------------------------------------------------------------- Pirates

# ------------------------------------------------------------------------------------------------- Warlord

# ------------------------------------------------------------------------------------------------- Alien

# -------------------------------------------------------------------------------------------------------------------------------------------------------- UCH and Admin POIs
     - '0 : 1.0,   1 : 0.0,  2 : 0.0,  3 : 0.0,  4 : 0.0,  5 : 0.0,  6 : 0.0,  7 : 0.0,  8 : 0.0'                 # 1 - UCH Research Vessel

# -------------------------------------------------------------------------------------------------------------------------------------------------------- Asteroid Fields
     - '0 : 0.0,   1 : 0.0,  2 : 0.0,  3 : 0.0,  4 : 0.3,  5 : 0.4,  6 : 0.3,  7 : 0.0,  8 : 0.0'                 # 1 - Asteroid Fields
     - '0 : 0.6,   1 : 0.2,  2 : 0.2,  3 : 0.0,  4 : 0.0,  5 : 0.0,  6 : 0.0,  7 : 0.0,  8 : 0.0'                 # 2 - Rich Asteroid Fields

# -------------------------------------------------------------------------------------------------------------------------------------------------------- Stations
     - '0 : 1.0,   1 : 0.0,  2 : 0.0,  3 : 0.0,  4 : 0.0,  5 : 0.0,  6 : 0.0,  7 : 0.0,  8 : 0.0'                 # 1 - Polaris Trade Station

# -------------------------------------------------------------------------------------------------------------------------------------------------------- Anomalies
     - '0 : 0.5,   1 : 0.4,  2 : 0.1,  3 : 0.0,  4 : 0.0,  5 : 0.0,  6 : 0.0,  7 : 0.0,  8 : 0.0'                 # 1 - Voidium Mining

# -------------------------------------------------------------------------------------------------------------------------------------------------------- Events
     - '0 : 0.9,   1 : 0.1,  2 : 0.0,  3 : 0.0,  4 : 0.0,  5 : 0.0,  6 : 0.0,  7 : 0.0,  8 : 0.0'                 # 1 - Random Events



  PlanetLists:           # Lable name depicts, in a descriptive way, the class or global or visual approach of the playfields summarized under this lable; playfields are added in the *Types sections
# ======================================================================================================================================================== Planets

# -------------------------------------------------------------------------------------------------------------- Gas Giants
    - 'Jupiter:0.6, Saturn: 0.4'                                                                                  # 1 Gas
    - 'JupiterOuter:0.45, SaturnOuter:0.35, NeptuneOuter:0.2'                                                     # 2 Gas Outer
# -------------------------------------------------------------------------------------------------------------- Stars
    - 'SunB:0.10, SunA:0.00, SunK:0.20, SunG:0.00, SunF:0.00, SunM:0.10, SunD:0.30, SunN2:0.30, SunA4V:0.00'      # 1 Companion Stars
# -------------------------------------------------------------------------------------------------------------- Rocky Planets
    - 'Lava3:0.3, Lava2:0.45, Midnight:0.25'                                                                         # 1 Hot
    - 'Desert:0.5, Arid:0.2, DesertOasis:0.0, DesertBlack:0.3'                                                    # 2 Desert
    - 'Dead:1'                                                                                                    # 3 Dead
    - 'Temperate:0.7, Tropical:0.1, Swamp:0.2, Irradiated:0.0, Jungle:0.0'                                        # 4 Temperate
    - 'Ocean:1'                                                                                                   # 5 Ocean
    - 'Alien:1'                                                                                                   # 6 Alien
    - 'Snow:1.0, Ice:0.0'                                                                                         # 7 Snow
    - 'Barren:0.5, BarrenHot:0.5'                                                                                 # 8 Barren
    - 'Plasma:1.0, AlienLegacy:0.0, ProgenitorCore:0.0, IceGiant: 0.0'                                            # 9 Exotic
# -------------------------------------------------------------------------------------------------------------------------------------------------------- Faction Planets
    - 'DeadWastelanders:1'                                                                                                    # 1 DeadWastelanders
# ======================================================================================================================================================== Sector POIs
# ------------------------------------------------------------------------------------------------- Main
    - 'TradingStationMain:1'              # 1 Trading Station
# ------------------------------------------------------------------------------------------------- Zirax

# ------------------------------------------------------------------------------------------------- Polaris

# ------------------------------------------------------------------------------------------------- Trader

# ------------------------------------------------------------------------------------------------- Colonists
    - 'SectorPOIColonistsScrapyard:1.0'
# ------------------------------------------------------------------------------------------------- Pirates

# ------------------------------------------------------------------------------------------------- Warlord

# ------------------------------------------------------------------------------------------------- Alien
# -------------------------------------------------------------------------------------------------------------- UCH and Admin
    - 'UCHResearchShip:1.0'                                                                                         # 1 UCH Research Vessel
# -------------------------------------------------------------------------------------------------------------- Asteroid Fields
    - 'AsteroidField_K:1.0, AsteroidFieldPirate:0.0, AsteroidFieldPolaris:0.0, AsteroidFieldZirax:0.0'              # 1 Asteroid Fields
    - 'AsteroidFieldRichGeneric:1'                                                                                  # 2 Rich Asteroid Fields
# -------------------------------------------------------------------------------------------------------------- Stations
    - 'TradeStationPolaris:1.0'                                                                                  # 1 Polaris Trade Station

# -------------------------------------------------------------------------------------------------------------- Anomalies
    - 'VoidiumMiningT5:1.0'              # 1 Voidium Mining
# -------------------------------------------------------------------------------------------------------------- Events
    - 'PentaxidMining:0.5, SyndicateCasino:0.0, XenuanCarrier:0.0, PirateBattlestation:0.5'                      # 1 Random Events



# ======================================================================================================================================================== POIs
  POICountProbs: '0 : 0.00,  1 : 0.00,  2 : 0.00,  3 : 0.00,  4 : 0.00,  5 : 0.30,  6 : 0.30,  7 : 0.20,  8: 0.20'
# -------------------------------------------------------------------------------------------------------------------------------------------------------- POI counts
  POIs: 'SpaceEmpty: 0.00, POICombatT4: 0.20, POIExploreT3: 0.30, POIMiningT3: 0.50'
# --------------------------------------------------------------------------------------------------------------------------------------------------------

# =================================================================================================================================================================================
#                                                                                                                POIs
# =================================================================================================================================================================================
  POITypes:
# ======================================================================================================================================================================================================
# ================================================================================================================================================================================= Random Sector POIs
# ======================================================================================================================================================================================================

# -------------------------------------------------------------------------- SpaceEmpty
      - Name: SpaceEmpty
        Color: [0.3, 0.3, 0.3]
        Icon: Triangle
        Placement:
            - InnerSystem
            - HabitableHot
            - HabitableTemperate
            - HabitableCold
            - OuterSystem
        HasOrbit: false
        HasTerrain: false
        PlayfieldLevel: [2,6]
        Playfields:
            - SpaceEmpty

# -------------------------------------------------------------------------- POI_Combat
      - Name: POI_Combat
        Icon: Triangle
        Color: [1, 0, 0]
        Placement:
            - InnerSystem
            - HabitableHot
            - HabitableTemperate
            - HabitableCold
            - OuterSystem
        HasOrbit: false
        HasTerrain: false
        PlayfieldLevel: [2,6]
        Playfields:
            - EdenSpaceK_POI_CombatBattle1, 0.5
            - EdenSpaceK_POI_Combat_C4_1, 0.5

# -------------------------------------------------------------------------- POI_Exploration
      - Name: POI_Exploration
        Icon: Triangle
        Color: [0, 1, 0.7]
        Placement:
            - InnerSystem
            - HabitableHot
            - HabitableTemperate
            - HabitableCold
            - OuterSystem
        HasOrbit: false
        HasTerrain: false
        PlayfieldLevel: [2,6]
        Playfields:
            - EdenSpaceK_POI_ExploreGrave1, 0.6
            - EdenSpaceK_POI_Explore_C3_1, 0.4

# -------------------------------------------------------------------------- POI_Mining
      - Name: POI_Mining
        Icon: Triangle
        Color: [0.62, 0.32, 0.17]
        Placement:
            - InnerSystem
            - HabitableHot
            - HabitableTemperate
            - HabitableCold
            - OuterSystem
        HasOrbit: false
        HasTerrain: false
        PlayfieldLevel: [2,6]
        Playfields:
            - EdenSpaceK_POI_Mining_C1_1

# =================================================================================================================================================================================
#                                                                                                                Orbits
# =================================================================================================================================================================================
  OrbitTypes:
# -------------------------------------------------------------------------- DefaultOrbit
      - Name: DefaultOrbit     # definition of default name 'DefaultOrbit' is mandatory
        Color: [0.3, 0.3, 0.3]
        Distance: [270, 870]
        HasOrbit: false
        HasTerrain: false
        PlayfieldLevel: [2,6]
        Playfields:
            - EdenSpaceK_Orbit

# =================================================================================================================================================================================
#                                                                                                                Stations
# =================================================================================================================================================================================
  StationTypes:
      # - Name: SpaceTradingStation
        # Color: [1, 1, 1]
        # Icon: Station
        # Distance: [200, 300]
        # Placement:
            # - InnerSystem
            # - HabitableHot
            # - HabitableTemperate
            # - HabitableCold
        # HasOrbit: false
        # HasTerrain: false
        # PlayfieldLevel: [2,10]
        # Playfields:
            # # - SpaceTradingStation
            # - EdenSpace_TradingStation
